### ISSUE TITLE
Elastic 6 support

### ISSUE THREAD

**Issue by Raz0r** [UnSciPreneur/e2eBridge#1]
Hi!

Elastic 6 deprecated the types of documents within an index: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

So now if you create mappings, you will get an error:

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [ethereum] as the final mapping would have more than 1 type: [block, transaction]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [ethereum] as the final mapping would have more than 1 type: [block, transaction]"},"status":400}
```

**Comment by UnSciPreneur** [comment]
Thanks for the news. I have only tested this app with Elastic 2.3 and 5.4 and was totally unaware that Elastic 6 brings those breaking changes. I should clarify this in the documentation. Replacing a single index with multiple types by multiple indices will require non-trivial code changes. As soon as I find time for testing I will provide a version that is compatible with Elastic 6.

**Comment by UnSciPreneur** [comment]
Totally forgot to mention that Elasticsearch 6 has been supported for more than a year now (since commit [cc0907758245f5efa948cf5eb3ef3c59a90f56ad](https://github.com/UnSciPreneur/e2eBridge/commit/cc0907758245f5efa948cf5eb3ef3c59a90f56ad).
