### ISSUE TITLE
Big Integers are not supported by elasticsearch

### ISSUE THREAD

**Issue by Raz0r** [UnSciPreneur/e2eBridge#2]
It is not possible to index blocks and transactions since they have BigInt fields such as `difficulty`, `totalDifficulty`, `value`, etc. Currently elasticsearch does not support this data type https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html. Which is why indexing fails: 

```
response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [totalDifficulty]"}],"type":"mapper_parsing_exception","reason":"failed to parse [totalDifficulty]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (9239341261939642000) out of range of long (-9223372036854775808 - 9223372036854775807)\\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@3fe7a0b2; line: 1, column: 1333]"}},"status":400}',
```

**Comment by UnSciPreneur** [comment]
You are probably right. I have checked that JavaScript can handle those integers (which it can) and I thought I had tested with Elastic. (Older versions of the tool simply divided by 10^6 to avoid this issue which was not nice either. 
I will go and investigate.

**Comment by UnSciPreneur** [comment]
I have committed [628b98d7305d8d11aecd6075fbb58f8680bf58fb](https://github.com/UnSciPreneur/e2eBridge/commit/628b98d7305d8d11aecd6075fbb58f8680bf58fb) to circumvent this issue. This is not beautiful but as long as Elasticsearch does not support any larger integer formats...

**Comment by Raz0r** [comment]
Hi,

I think that `block.difficulty` and `transaction.gasPrice` also need to be transformed.

**Comment by UnSciPreneur** [comment]
Hi,

I totally agree when it comes to `block.difficulty`. Commit [e39b176e29c72beabc32291c17600faf7b16c7c7](https://github.com/UnSciPreneur/e2eBridge/commit/e39b176e29c72beabc32291c17600faf7b16c7c7) already reflects that: We now divide both `block.difficulty` and `block.totalDifficulty` by 10^6.

We could also divide `transaction.gasPrice` by some factor. But given the fact that a naked value transaction costs 21'000 gas I do not expect anyone to issue an transaction with a gas price beyond 2^63 Wei: This would put the price of a value transaction north of 180'000 ETH... Or did I miss something here?
